#!/usr/bin/env node
// Install holder-kit as a skill for a LOCAL Hermes Agent (Nous Research).
//
//   npm run hermes:install                          # read-only agent (default)
//   npm run hermes:install -- --broadcast free-mints   # may send zero-price mints
//   npm run hermes:install -- --broadcast all          # may send anything (ceilings apply)
//   npm run hermes:install -- --uninstall
//
// Writes  $HERMES_HOME/skills/holder-kit/   (default ~/.hermes/skills/holder-kit)
//   SKILL.md             the skill, with this repo's real paths filled in
//   references/AGENTS.md the full agent operating contract
//   scripts/hk.mjs       the ONLY entry point the agent is told to use: runs the
//                        CLI with HOLDER_KIT_AGENT=1 and the policy below
//   policy.json          the broadcast level YOU chose — re-run this installer
//                        to change it. Env vars from the agent are ignored.
//
// Nothing secret is copied: no vault, no password, no RPC keys.
import { mkdirSync, writeFileSync, readFileSync, copyFileSync, rmSync, existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const argv = process.argv.slice(2);
const opt = (name, fallback) => {
  const i = argv.indexOf(`--${name}`);
  return i === -1 ? fallback : argv[i + 1];
};

const hermesHome = resolve(opt('hermes-home', process.env.HERMES_HOME || join(homedir(), '.hermes')));
const dest = resolve(opt('dest', join(hermesHome, 'skills', 'holder-kit')));
const level = String(opt('broadcast', 'none')).toLowerCase();

if (argv.includes('--uninstall')) {
  if (existsSync(join(dest, 'SKILL.md'))) {
    rmSync(dest, { recursive: true, force: true });
    console.log(`removed ${dest}`);
  } else {
    console.log(`nothing installed at ${dest}`);
  }
  process.exit(0);
}

if (!['none', 'free-mints', 'all'].includes(level)) {
  console.error(`--broadcast must be one of: none, free-mints, all (got "${level}")`);
  process.exit(1);
}

const nodeMajor = Number(process.versions.node.split('.')[0]);
if (nodeMajor < 20) {
  console.error(`holder-kit needs Node 20+, this is ${process.versions.node}`);
  process.exit(1);
}
if (!existsSync(join(ROOT, 'node_modules', 'viem'))) {
  console.error('dependencies missing — run `npm install` in the repo first');
  process.exit(1);
}

mkdirSync(join(dest, 'scripts'), { recursive: true });
mkdirSync(join(dest, 'references'), { recursive: true });

const cli = join(ROOT, 'bin', 'holder-kit.mjs');
const wrapper = join(dest, 'scripts', 'hk.mjs');
// JSON.stringify makes the paths safe to embed as JS string literals
// (Windows backslashes, spaces, quotes).
writeFileSync(
  wrapper,
  `#!/usr/bin/env node
// holder-kit agent wrapper — generated by scripts/install-hermes.mjs. Do not edit;
// re-run the installer instead. Forces agent mode and the holder's chosen policy.
import { spawnSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
const CLI = ${JSON.stringify(cli)};
const ROOT = ${JSON.stringify(ROOT)};
const POLICY = ${JSON.stringify(join(dest, 'policy.json'))};
let level = 'none';
try { level = JSON.parse(readFileSync(POLICY, 'utf8')).broadcast || 'none'; } catch {}
const env = { ...process.env, HOLDER_KIT_AGENT: '1', HOLDER_KIT_AGENT_BROADCAST: level, NO_COLOR: '1' };
delete env.HOLDER_KIT_AUTO;            // the agent never inherits "auto everything"
delete env.HOLDER_KIT_NEW_PASSWORD;
const r = spawnSync(process.execPath, [CLI, ...process.argv.slice(2)], { cwd: ROOT, env, stdio: 'inherit' });
process.exit(r.status ?? 1);
`,
  { mode: 0o755 }
);

writeFileSync(
  join(dest, 'policy.json'),
  JSON.stringify({ broadcast: level, setBy: 'holder via scripts/install-hermes.mjs', at: new Date().toISOString() }, null, 2) + '\n'
);

const skill = readFileSync(join(ROOT, 'agents', 'SKILL.md'), 'utf8')
  .replaceAll('{{HK_WRAPPER}}', wrapper)
  .replaceAll('{{HK_HOME}}', ROOT);
writeFileSync(join(dest, 'SKILL.md'), skill);
copyFileSync(join(ROOT, 'agents', 'AGENTS.md'), join(dest, 'references', 'AGENTS.md'));

// Smoke test: the wrapper runs, agent mode is on, and the policy took.
import('node:child_process').then(({ spawnSync }) => {
  const r = spawnSync(process.execPath, [wrapper, 'agents'], { encoding: 'utf8' });
  const on = /agent mode:\s*ON/.test(r.stdout || '');
  const lvl = new RegExp(`broadcast:\\s*${level}`).test(r.stdout || '');
  console.log(`\nholder-kit skill installed for Hermes`);
  console.log(`  skill    : ${join(dest, 'SKILL.md')}`);
  console.log(`  wrapper  : ${wrapper}`);
  console.log(`  policy   : broadcast = ${level}`);
  console.log(`  self-test: ${on && lvl ? 'OK (agent mode on, policy applied)' : 'FAILED — run the wrapper by hand: node ' + wrapper + ' agents'}`);
  console.log(`\nNext:`);
  console.log(`  1. Make sure YOU have run setup once:  node bin/holder-kit.mjs setup`);
  console.log(`  2. Restart Hermes (or start a new session) so it picks up the skill.`);
  console.log(`  3. Ask it: "use holder-kit to check my setup"\n`);
  if (level !== 'none') {
    console.log(`  Note: the agent can broadcast ${level === 'all' ? 'ANY transaction' : 'zero-price mints'} from your vault, within the ceilings.`);
    console.log(`  Downgrade any time: npm run hermes:install -- --broadcast none\n`);
  }
  process.exitCode = on && lvl ? 0 : 1;
});
